[package]
name = "program_gen"
version = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "program_gen"
path = "src/main.rs"

[dependencies]
precomp-arith-eq = { workspace = true }
path-clean = "1.0"
clap = "4.5.50"
env = "1.0.1"
