[package]
name = "program_gen"
version = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "program_gen"
path = "src/main.rs"

[dependencies]
path-clean = "1.0"
clap = "4.5.50"
env = "1.0.1"
# precomp-arith-eq = { git = "https://github.com/0xPolygonHermez/zisk.git" }
# precomp-arith-eq-384 = { git = "https://github.com/0xPolygonHermez/zisk.git" }
# precomp-big-int = { git = "https://github.com/0xPolygonHermez/zisk.git" }
# Local development
precomp-arith-eq = { path = "../../../zisk/precompiles/arith_eq" }
precomp-arith-eq-384 = { path = "../../../zisk/precompiles/arith_eq_384" }
precomp-big-int = { path = "../../../zisk/precompiles/big_int" }
