[package]
name = "substrate-bn-lib"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
ziskos = { workspace = true }
substrate-bn = { workspace = true }

[lints]
workspace = true


