[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "add256/program",
    "arith_eq_384_gen/program",
    "arith_eq_gen/program",
    "arith_eq_pow/program",
    "bls12_381/program",
    "bn254/program",
    "diagnostic/program",
    "fcall/program",
    "fcall_msb/program",
    "keccak/program",
    "sha256/program",
    "modexp/program",
    "prover_killers/program",
    "secp256k1/program",
    "blst/program",
    "substrate_bn/program",
]
resolver = "2"

[profile.dev]
debug = 0  # No debug info to prevent linker overflow

[profile.release]
opt-level = 3

[profile.bench]
opt-level = 3

[workspace.dependencies]
# ziskos = { git = "https://github.com/0xPolygonHermez/zisk.git", branch = "pre-develop-0.16.0" }
# Local development
ziskos = { path = "../../zisk/ziskos/entrypoint" }
rand = "0.8"

blst = { version = "0.3.15", features = ["portable"] }
substrate-bn = { version = "0.6.0" }

[patch.crates-io]
blst = { git = "https://github.com/0xPolygonHermez/zisk-patch-blst.git", branch = "zisk-patch/v0.3.15" }
# substrate-bn = { git = "https://github.com/0xPolygonHermez/zisk-patch-bn.git", tag = "patch-0.6.0-zisk-0.15.0" }
# Local development
# blst = { path = "../../patches/zisk-patch-blst/bindings/rust" }
substrate-bn = { path = "../../patches/zisk-patch-bn" }

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_vendor, values("zisk"))'] }